events {}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    upstream budget_service {
        server budget_service:8000;
    }

    upstream report_service {
        server report_service:8000;
    }

    upstream notification_service {
        server notification_service:8000;
    }

    server {
        listen 80;

        location /budget/ {
            proxy_pass http://budget_service/;
        }

        location /reports/ {
            proxy_pass http://report_service/;
        }

        location /notifications/ {
            proxy_pass http://notification_service/;
        }
    }
}
